server:
  port: 8080

spring:
  application:
    name: bookstore-api

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookstoredb}
    username: ${DB_USER:bookstore}
    password: ${DB_PASS:bookstore123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update          # use 'validate' in production; 'update' for POC
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never               # set to 'always' to run data.sql on startup

# SpringDoc / Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    com.bookstore: DEBUG
    org.springframework.security: INFO
